### ISSUE TITLE
.Net core console app support

### ISSUE THREAD

**Issue by AlexeyBogdan95** [fpanaccia/Wkhtmltopdf.NetCore#10]
Good time!

I'd like to know if `Wkhtmltopdf.NetCore` supports console app. In the description you mentioned only asp.net core. I wanna clarify it.

Thank you!

**Comment by fpanaccia** [comment]
Hi!, sorry for the delay....3.0 caused me a little trouble! i would say is technically possible, some time ago i have done it with net core 2.2, i haven't tested it with 2.2, which net core version are you using?

**Comment by AlexeyBogdan95** [comment]
Hi @fpanaccia. I'm using 2.2. And it doesn't work in console app. When I switched from `HostBuilder` to `WebHostBuilder` it started working fine.

**Comment by fpanaccia** [comment]
hi, i'm glad that you got that working, yeah it uses the razor engine so, it will need that.

If you need any help, just ask and i will try to help.
