### ISSUE TITLE
Images are not reflected in a file when I run an application in Docker

### ISSUE THREAD

**Issue by AlexeyBogdan95** [fpanaccia/Wkhtmltopdf.NetCore#12]
Hello!

I have an application which creates PDF pages that contain images.
When I run it locally it works perfect.

Unfortunately, when I run it in docker images are not reflected in PDF files(css works fine).

Did you face such an issue?

Thank you!

**Comment by fpanaccia** [comment]
Hi, sorry for the delay, i was on vacations, did you solve it? it seems to be a problem of differents PATH or that the images are not being copied were you wanted.
