### ISSUE TITLE
services.AddWkhtmltopdf HostingEnvironment marked obsolete and replaced on .net core 3.0

### ISSUE THREAD

**Issue by JingLi-kooboo** [fpanaccia/Wkhtmltopdf.NetCore#14]
![image](https://user-images.githubusercontent.com/20513064/72517419-532a1600-388e-11ea-9fc5-1d7069f938cd.png)

**Comment by fpanaccia** [comment]
Hi, sorry for the delay, what version are you using?
Have you tried the one version in preview?
In the following days i will be uploading a new version for 3.1

**Comment by fpanaccia** [comment]
Hi, have you tried the preview version? i just pushed a new stable one, and works perfectly with 301 and 3.1, if you have any issue, just let me know
