### ISSUE TITLE
Url & delay rendering

### ISSUE THREAD

**Issue by unruledboy** [fpanaccia/Wkhtmltopdf.NetCore#15]
Hi,

I tried to render a url ( https://echarts.apache.org/examples/en/editor.html?c=bar-gradient ) using HeaderPagingTest sample function. But it seems it could not handle delay and related resources properly.

I was wondering it could properly render pdf based on a url?

**Comment by fpanaccia** [comment]
Hi, sorry for the delay, yes, it can, the problem is javascript in that URL, WebClient, is an http client, it is not a headless browser. In another words, you should use another way to get the html.
