### ISSUE TITLE
It Gives editor error

### ISSUE THREAD

**Issue by kilic89** [fpanaccia/Wkhtmltopdf.NetCore#16]
I got below error code when I try to open project.
676 | ERROR | System.Exception: Exception of type 'System.Exception' was thrown.   at Microsoft.Internal.VisualStudio.Shell.Interop.IVsSolutionBuildOrderPrivate.GetBuildOrderList(Boolean fForceRecalculation, UInt32 cProjects, VsProjectBuildOrder[] pBuildOrder, UInt32& pValidationId)   at Microsoft.VisualStudio.ErrorListPkg.Shims.TaskListBase.RecalculateProjectRank()   at Microsoft.VisualStudio.ErrorListPkg.Shims.TaskListBase.OnEntriesChanged(Object sender, EntriesChangedEventArgs e)   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args) --- End of stack trace from previous location where exception was thrown ---   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) |   |   | Editor or Editor Extension | 2020/02/06 06:47:44.596
-- | -- | -- | -- | -- | -- | --

**Comment by fpanaccia** [comment]
Hi, sorry for the delay, i am not able to reproduce this issue, what version of visual studio are you using? and what os are you using?
