### ISSUE TITLE
WEB API

### ISSUE THREAD

**Issue by freefred81** [fpanaccia/Wkhtmltopdf.NetCore#18]
Hi (or ciao :) ) is it possibile to use it in a pure WEBAPI project ? without view? .... if yes how to replace the view params in the pdf method? thnx!

**Comment by fpanaccia** [comment]
Hi! sorry for the delay, it is possible, you could simply send a path to the view or send the hardcoded html
Here is an example!

[WebApplication1.zip](https://github.com/fpanaccia/Wkhtmltopdf.NetCore/files/4352705/WebApplication1.zip)
