### ISSUE TITLE
Error Running Locally on Mac

### ISSUE THREAD

**Issue by mtpultz** [fpanaccia/Wkhtmltopdf.NetCore#22]
Having an issue running this package locally (command F5) on Mac, but the same .Net Core project generates PDFs with no issues on a PC.

I've followed the setup and example project you have posted, and looked at the OS check in your [driver](https://github.com/fpanaccia/Wkhtmltopdf.NetCore/blob/3b7612bd1e700997e4f6dd047740831d0318b26c/Wkhtmltopdf.NetCore/WkhtmlDriver.cs#L35), but on Mac I always get this error:

```
[11:16:02 ERR] HTTP POST /api/registration/2 responded 500 in 12210.6616 ms
System.ComponentModel.Win32Exception (13): Permission denied
   at Wkhtmltopdf.NetCore.WkhtmlDriver.Convert(String wkhtmlPath, String switches, String html)
   at Wkhtmltopdf.NetCore.GeneratePdf.GetPDF(String html)
   at Prime.Services.PdfService.Generate(String htmlContent)
```

I've configured the service, and provided a relative path to the wkhtmltopdf files that contains the /Linux, /Mac, and /Windows folders:

```
services.AddWkhtmltopdf("./Resources/wkhtmltopdf");
```

And added the item group to .csproj:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RootNamespace>Prime</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  ... // Removed for brevity

  <ItemGroup>
    <None Update="Resources\wkhtmltopdf\Linux\wkhtmltopdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\wkhtmltopdf\Mac\wkhtmltopdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\wkhtmltopdf\Windows\wkhtmltopdf.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
```

**Comment by fpanaccia** [comment]
Hi, sorry for the delay, did you fixed it?

**Comment by mtpultz** [comment]
I did.  It was a stupid mistake that I should have guessed from the error.  I just needed to sleep on it.  I didn't set the chmod on the local wkhtmltopdf file on a Mac, which you don't need to do on a PC.  Thanks for the reply.  This is a great package for integrating with .Net Core.
