### ISSUE TITLE
Possible to expose Replace Options ?

### ISSUE THREAD

**Issue by julienGrd** [fpanaccia/Wkhtmltopdf.NetCore#23]
Hello, and thanks for your library !

Do you think its possible to expose te replace parameter of wkhtmltopdf ? (https://stackoverflow.com/questions/26985285/how-to-use-replace-in-wkhtmltopdf) it will allow to use custom variable in header and footer, otherwise we can only load static html on these part !

Thanks !

**Comment by Ayiadim** [comment]
I've created a pull request for this [here](https://github.com/fpanaccia/Wkhtmltopdf.NetCore/pull/24)

**Comment by fpanaccia** [comment]
Hi! sorry for the delay thanks for the pull request!, this weekend i will take a look at the PR and add the new functionality to the example

**Comment by fpanaccia** [comment]
Hi!, sorry for the delay! i have merge the merge request, pushed the new version of the nuget (https://www.nuget.org/packages/Wkhtmltopdf.NetCore/3.0.1) and also pushed an example fo how to use it in this commit https://github.com/fpanaccia/Wkhtmltopdf.NetCore.Example/commit/cb5fff6a5879857720871e6f8b5f6b2445b1b63d (the method FooterTest in the TestViewsController.cs

Thanks for the request @julienGrd and thanks for the help @Ayiadim !
