### ISSUE TITLE
Request - remove MVC dependency

### ISSUE THREAD

**Issue by akdor1154** [fpanaccia/Wkhtmltopdf.NetCore#4]
The core functionality of this library does not require MVC at all, it makes me a bit sad to have to pull in all of AspNetCore.MVC anyway. (I want to use it in an old .NET Framework project that's still on MVC4). Happy to submit a pull request but it would probably consist of moving the MVC-dependent code into your example project or something, which seems a bit invasive for a drive-by PR to your project. :)

**Comment by fpanaccia** [comment]
Hi, sorry for the delay, i understand your requirement, but i need the library to work this way (at least for now).
I guess i could do another nuget, with the mvc part alone, but as you can see i already engage in a change for the library, maybe for another release.

**Comment by akdor1154** [comment]
No worries! :) i just wrote my own wrapper, was a very small amount of code.

**Comment by fpanaccia** [comment]
yeap, the core functionality it is just one class
