### ISSUE TITLE
_generatePdf.GetByteArrayViewInHtml(htmlView,data) not working

### ISSUE THREAD

**Issue by thanhnamrei** [fpanaccia/Wkhtmltopdf.NetCore#44]
- I have two project: api and classlibary
- In classlibary:  I install nug Wkhtmltopdf.NetCore and write function printPdf call func: await _generatePdf.GetByteArrayViewInHtml(htmlView, data);
- In Api project:  Acction generate printPdf form classlib, throw excel
Cannot find reference assembly 'Microsoft.AspNetCore.Antiforgery.dll' file for package Microsoft.AspNetCore.Antiforgery.Reference'
But  use _generatePdf.GetByteArray("Views/Test.cshtml", data) every working correc

**Comment by Sotolotl** [comment]
Did you ever get to the bottom of this/find a work-around? I'm having the same problem.

**Comment by thanhnamrei** [comment]
> Did you ever get to the bottom of this/find a work-around? I'm having the same problem.

no, i used Haukcode.WkHtmlToPdfDotNet nuget, but it's not support cshtml => pdf, only html to pdf

**Comment by Sotolotl** [comment]
Ah, that's a shame. Thanks for the suggestion, I'll look into it :)

**Comment by tyler-boyd** [comment]
I ran into this too, and found [this related issue](https://github.com/toddams/RazorLight/issues/294). Adding `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` to the project that is doing the view rendering fixed the issue for me.
