### ISSUE TITLE
Injecting dependencies using scope

### ISSUE THREAD

**Issue by thug1705** [fpanaccia/Wkhtmltopdf.NetCore#51]
Hi @fpanaccia, firstly thanks for the library.

I am trying to use in my project where I have background task that suppose to generate pdfs for one or more data elements. I am having issues when I am trying to inject depenendencies using service provider. I am trying to do like this

```
var tempDataProvider = serviceScope.ServiceProvider.GetRequiredService<ITempDataProvider>();
var razorViewEngine = serviceScope.ServiceProvider.GetRequiredService<IRazorViewEngine>();
var razorViewStringRenderer = serviceScope.ServiceProvider.GetRequiredService<IRazorViewToStringRenderer>();
var pdfGenerator = serviceScope.ServiceProvider.GetRequiredService<IGeneratePdf>();
```
However when I run I am getting following exception

![image](https://user-images.githubusercontent.com/29228328/105872050-daf24680-5ff1-11eb-8d94-eb19cc16a0e7.png)

Any ideas how to this, am I missing some dependencies ?

**Comment by gurustron** [comment]
Can you please add full repro somewhere?

**Comment by thug1705** [comment]
Hi @gurustron thanks for you respond, unfortunately I can't share source code. Anyway issue was related to my code, rather then library itself therefor I will close the issue.
