### ISSUE TITLE
Error in Linux

### ISSUE THREAD

**Issue by jasonlaw** [fpanaccia/Wkhtmltopdf.NetCore#53]
May I know how to fix the following error?

[03/01/2021 09:36:41] ErrorKind:Internal 
System.Exception: /var/aspnetcore/viqcommunitystaging/Rotativa/Linux/wkhtmltopdf: error while loading shared libraries: libpng15.so.15: cannot open shared object file: No such file or directory

Also, may I know where do you get the latest wkhtmltopdf file?

Many thanks.

**Comment by enteezgit** [comment]
try 
`apt-get install libpng16-16`

I had libjpeg.so.62 and it was resolved with  `apt-get install libjpeg62`

This was on Ubuntu 20.04 though

**Comment by jasonlaw** [comment]
Thanks!
