### ISSUE TITLE
Error on run Docker 

### ISSUE THREAD

**Issue by edu-eng** [fpanaccia/Wkhtmltopdf.NetCore#67]
EXCEPTION: System.ComponentModel.Win32Exception (13): Permission denied\n   at Wkhtmltopdf.NetCore.GeneratePdf.GetByteArray[T](String View, T model)\n

**Comment by Jefferycheng** [comment]
I thought this exception is because your dotnet app don't have enough permission to get the wkhtmltopdf file.

See the example repository.

https://github.com/fpanaccia/Wkhtmltopdf.NetCore.Example/blob/master/Rotativa/Dockerfile#L15

**Comment by edu-eng** [comment]
Thank you it worked!
