### ISSUE TITLE
Can't find view when running published release build

### ISSUE THREAD

**Issue by MichielCornilleESC** [fpanaccia/Wkhtmltopdf.NetCore#7]
Hello
The following code works in dev, but not on production (deployed to IIS)

```
     var viewAsPdf = new Wkhtmltopdf.NetCore.ViewAsPdf(_hostingEnvironment.ContentRootPath)
            {
                PageMargins = new Margins(0, 0, 0, 0),
                PageSize = Size.A4,
                IsLowQuality = false
            };

            return  await viewAsPdf.GetByteArray("Views/Contract.cshtml", sale);  
```

It apparently can't find the view, which makes sense, since the views are compiled into the dll.
I don't know however how to get it running.

**Comment by fpanaccia** [comment]
Hi, which version of the library are you using? and what OS?

**Comment by MichielCornilleESC** [comment]
I am on 1.1.3, I see there is a 2.0.1, I'll update to that version and report back to you. OS is Windows Server with IIS.

**Comment by MichielCornilleESC** [comment]
2.0.1 resolved all my issues, thanks.

**Comment by fpanaccia** [comment]
nice, thanks!
