### ISSUE TITLE
How to set options like header?

### ISSUE THREAD

**Issue by Saad-Alothman** [fpanaccia/Wkhtmltopdf.NetCore#8]
Thank you for sharing the library with the community!

I was just playing around with the library and i tried to set the header for the PDF, 
after looking at the code, i was able to do that by casting IGeneratePdf to the Implementation (GeneratePdf) , from there i can access the header.

is there another way to do it?

**Comment by fpanaccia** [comment]
Hi, sorry for the delay, actually i have never had the need to use headers.

Currently, im with little free time, so if you wanna, you can show how you do it, and we can add it to the library, or just make the PR

**Comment by fpanaccia** [comment]
Hi, i just pushed a new version, and you will find that you can do it without the need to do some casting
