### ISSUE TITLE
.net core 3.0 support

### ISSUE THREAD

**Issue by matt748** [fpanaccia/Wkhtmltopdf.NetCore#9]
Hi, thanks for creating this library, it works great in a .net core 2.1 project, but currently getting an error in a ASP.Net Core 3.0 project...

> System.TypeLoadException: 'Could not load type 'Microsoft.AspNetCore.Hosting.Internal.HostingEnvironment' from assembly 'Microsoft.AspNetCore.Hosting, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.'

Any ideas when you will be adding support for Core 3.0? I'm using preview 8 at the moment, but its only a few weeks until general release :)

**Comment by fpanaccia** [comment]
Hi!, sorry for the delay, i'm guessing between this week i will release a preview version for 3.0

**Comment by matt748** [comment]
Thanks, 3.0 is being released today I think, so good timing!

**Comment by fpanaccia** [comment]
Hi!, this version seems to be working (at least in the example project)

https://www.nuget.org/packages/Wkhtmltopdf.NetCore/3.0.1-preview

**Comment by matt748** [comment]
Yes that works a treat, thank you so much!

**Comment by fpanaccia** [comment]
Your welcome!
